id: I24E34FE7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:54:54+00:00'
last_modified: '2022-06-08T09:45:24.367162+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN1657
  title: སཾ་བོད་སྐད་གཉིས་ཤན་སྦྱར་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F984:
      image_group_id: I3CN1659
      title: ''
      total_pages: 356
      order: 1
      base_file: F984.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
