id: P009260
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1657
  title: སཾ་བོད་སྐད་གཉིས་ཤན་སྦྱར་ཚིག་མཛོད།
  author: ''
  volumes:
    c7f6684037524c69bc717eb1a2fc7417:
      image_group_id: I3CN1659
      title: ''
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
