id: P009260
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:27.112573
source_metadata:
  id: bdr:W3CN1657
  title: སཾ་བོད་སྐད་གཉིས་ཤན་སྦྱར་ཚིག་མཛོད།
  author: ''
  volumes:
    c7f6684037524c69bc717eb1a2fc7417:
      image_group_id: I3CN1659
      title: ''
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
